/******************************************************************************
 *                            blk_ip.cpp
 *
 * Generated by QCG in January, 28, 2019 at 13:54:45
 *           on system: raspberrypi (Linux 4.14.79-v7+ armv7l)
 *
 * User: QSDL
 *
 * Copyright (C) 1995-98 Marc Diefenbruch (md@informatik.uni-essen.de)
 *                and Joerg Ruehl (jruehl@informatik.uni-essen.de)
 *
 * All rights reserved.
 *
 *****************************************************************************/

/******************************************************************************
 * Includes
 *****************************************************************************/

#include "blk_ip.h"
#include "pcs_ip_activity.h"

#include <SCL/SCScheduler.h>

/******************************************************************************
 * Konstanten (Synonyme) auf Blockebene (statisch)
 *****************************************************************************/

SCInteger blk_ip::syn_own_address;

/******************************************************************************
 * Initialisierung der Prozesstypen und der Prozess-IDs (statisch)
 *****************************************************************************/

blk_ip::PcsType_activity * blk_ip::pcs_type_activity = NULL;

SCProcess *blk_ip::PcsType_activity::NewInstance(const SCProcessID creatorID,
                                                 SCDataType *actual_params) const
{
  (void)actual_params;

  return new pcs_ip_activity(creatorID, this);
}

SCProcess *blk_ip::PcsType_activity::NewInstance(SCMem &save_area) const
{
  return new pcs_ip_activity(save_area);
}


/******************************************************************************
 * Initialisierungsfunktion der SDL-Blockklasse (statisch)
 *****************************************************************************/

SCBoolean blk_ip::Initialize(void)
{
  SCBoolean result = true;

  if (SCScheduler::IsVerbose())
  {
    std::cout << "Initializing block ip..." << std::endl;
  }

  /****************************************************************************
   * Datentypen auf Blockebene initialisieren:
   ***************************************************************************/

  syn_own_address = 111;

  /****************************************************************************
   * Prozesstypen initialisieren:
   ***************************************************************************/

  pcs_type_activity = new PcsType_activity(pcs_type_id_activity,
                                           "activity", 1, kSCUnlimitedQueueLength);

  /****************************************************************************
   * Statische Initialisierungsfunktionen der Prozesse aufrufen:
   ***************************************************************************/

  result = result & pcs_ip_activity_data::Initialize();
  result = result & pcs_ip_activity::Initialize();

  return result;
}

/******************************************************************************
 * Beendigungsfunktion der SDL-Blockklasse (statisch)
 *****************************************************************************/

void blk_ip::Finish(void)
{
  /****************************************************************************
   * Prozesstypen zerstoeren:
   ***************************************************************************/

  delete pcs_type_activity;

  /****************************************************************************
   * Statische Beendigungsfunktionen der Prozesse aufrufen:
   ***************************************************************************/

  pcs_ip_activity_data::Finish();
  pcs_ip_activity::Finish();
}

/******************************************************************************
 * Konstruktor des Blocks
 *****************************************************************************/

blk_ip::blk_ip(void)
{
}

/******************************************************************************
 * Destruktor des Blocks
 *****************************************************************************/

blk_ip::~blk_ip(void)
{
}

