/******************************************************************************
 *                            blk_medium.cpp
 *
 * Generated by QCG in January, 28, 2019 at 13:54:45
 *           on system: raspberrypi (Linux 4.14.79-v7+ armv7l)
 *
 * User: QSDL
 *
 * Copyright (C) 1995-98 Marc Diefenbruch (md@informatik.uni-essen.de)
 *                and Joerg Ruehl (jruehl@informatik.uni-essen.de)
 *
 * All rights reserved.
 *
 *****************************************************************************/

/******************************************************************************
 * Includes
 *****************************************************************************/

#include "blk_medium.h"
#include "pcs_medium_transport.h"

#include <SCL/SCScheduler.h>

/******************************************************************************
 * Initialisierung der Prozesstypen und der Prozess-IDs (statisch)
 *****************************************************************************/

blk_medium::PcsType_transport * blk_medium::pcs_type_transport = NULL;

SCProcess *blk_medium::PcsType_transport::NewInstance(const SCProcessID creatorID,
                                                      SCDataType *actual_params) const
{
  (void)actual_params;

  return new pcs_medium_transport(creatorID, this);
}

SCProcess *blk_medium::PcsType_transport::NewInstance(SCMem &save_area) const
{
  return new pcs_medium_transport(save_area);
}


/******************************************************************************
 * Initialisierungsfunktion der SDL-Blockklasse (statisch)
 *****************************************************************************/

SCBoolean blk_medium::Initialize(void)
{
  SCBoolean result = true;

  if (SCScheduler::IsVerbose())
  {
    std::cout << "Initializing block medium..." << std::endl;
  }

  /****************************************************************************
   * Prozesstypen initialisieren:
   ***************************************************************************/

  pcs_type_transport = new PcsType_transport(pcs_type_id_transport,
                                             "transport", 1,
                                             kSCUnlimitedQueueLength);

  /****************************************************************************
   * Statische Initialisierungsfunktionen der Prozesse aufrufen:
   ***************************************************************************/

  result = result & pcs_medium_transport_data::Initialize();
  result = result & pcs_medium_transport::Initialize();

  return result;
}

/******************************************************************************
 * Beendigungsfunktion der SDL-Blockklasse (statisch)
 *****************************************************************************/

void blk_medium::Finish(void)
{
  /****************************************************************************
   * Prozesstypen zerstoeren:
   ***************************************************************************/

  delete pcs_type_transport;

  /****************************************************************************
   * Statische Beendigungsfunktionen der Prozesse aufrufen:
   ***************************************************************************/

  pcs_medium_transport_data::Finish();
  pcs_medium_transport::Finish();
}

/******************************************************************************
 * Konstruktor des Blocks
 *****************************************************************************/

blk_medium::blk_medium(void)
{
}

/******************************************************************************
 * Destruktor des Blocks
 *****************************************************************************/

blk_medium::~blk_medium(void)
{
}

