/******************************************************************************
 *                            Templates.cpp
 *
 * Generated by QCG in January, 28, 2019 at 13:54:45
 *           on system: raspberrypi (Linux 4.14.79-v7+ armv7l)
 *
 * User: QSDL
 *
 * Copyright (C) 1995-98 Marc Diefenbruch (md@informatik.uni-essen.de)
 *                and Joerg Ruehl (jruehl@informatik.uni-essen.de)
 *
 * All rights reserved.
 *
 *****************************************************************************/


#include <SCL/SCEnvironment.h>

#include <SCL/SCArray.tmpl.h>
#include <SCL/SCList.tmpl.h>
#include <SCL/SCString.tmpl.h>
#include <SCL/SCSyntype.tmpl.h>
#include "pcs_application_loadgenerator.h"
#include "pcs_application_applicationmanager.h"
#include "pcs_tcp_manager.h"
#include "pcs_tcp_port.h"
#include "pcs_ip_activity.h"
#include "pcs_medium_transport.h"

template class SCSyntype<SCInteger>;
template class SCArray<sys_qtcp::DataType_retransmitpacket>;
template class SCArray<SCPid>;
//template class SCSyntype<SCInteger>;
//template class SCArray<SCInteger>;
//template class SCArray<SCPid>;
template class SCArray<SCBoolean>;

